### ISSUE TITLE
Get warnings in console

### ISSUE THREAD

**Issue by 1951FDG** [tjeffree/Brackets-ExtensionHighlight#19]
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file://localhost/Volumes/Backup/Users/administrator/Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at file://localhost/Users/administrator/Library/Application%20Support/Brackets/extensions/user/tjeffree.extensionhighlighter/main.js:48:9
    at Object.<anonymous> (file://localhost/Users/administrator/Library/Application%20Support/Brackets/extensions/user/tjeffree.extensionhighlighter/main.js:55:7)

**Comment by tjeffree** [comment]
Hi, thanks for the report. I'll take a look at this soon!

**Comment by 1951FDG** [comment]
Thanks!
